---

- name: Enable the EPEL Repository
  ini_file: dest=/etc/yum.repos.d/epel.repo
            section=epel
            option=enabled
            value=1

- name: Apply all system updates (yum -y update)
  yum: name="*" state=latest
