---
- name: Key Distribution
  hosts: "{{ region }}:&key_{{ key_name }}"
  tasks:
  - name: GIO-itadm-key
    authorized_key: user="{{ ansible_user_id }}" key="{{ lookup('file', '~/.ssh/GIO-itadm.pub') }}"
