---

- name: Provision dgfamily EC2 Instance(s)
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
  - name: Launch new instance(s)
    local_action:
      module: ec2
      count: "{{ dgfamily_instance_count }}"
      instance_type: "{{ dgfamily_instance_type }}"
      image: "{{ ec2.ami.amazon_linux_hvm }}"
      region: "{{ region }}"
      vpc_subnet_id: "{{ ec2.vpc.private.b }}"
      group_id: "{{ ec2.sg.private0 }}"       
      key_name: "{{ ec2.kp.itadm }}"
      monitoring: no 
      assign_public_ip: no
      wait: yes
      wait_timeout: 500
      volumes:
      - device_name: /dev/xvda
        device_type: standard
        volume_size: 15
        delete_on_termination: true
      - device_name: /dev/xvdb
        device_type: standard
        volume_size: 21
        delete_on_termination: true
      - device_name: /dev/xvdc
        device_type: standard
        volume_size: 49
        delete_on_termination: true
    register: ec2info

  - name: Tag launched instance(s)
    local_action:
      module: ec2_tag
      resource: "{{ item.1.id }}"
      region: "{{ region }}"
      tags:
        Name: "dgfamily{{ '%03d' % ( 200 + item.0 + 1) }}"
        system: dgfamily
        environment: preprod
    with_indexed_items: ec2info.instances

  - name: Add all instance private IPs to host group
    local_action: add_host hostname={{ item.private_ip }} groupname=tag_system_dgfamily
    with_items: ec2info.instances

  - name: Waiting for SSH to come up
    local_action: wait_for host={{ item.private_ip }} port=22 delay=60 timeout=300 state=started
    with_items: ec2info.instances

#- name: Install dgfamily on EC2 Instance(s)
#  include: configure-dgfamily.yml
