---

- name: Provision awsutils EC2 Instance
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:

  - include_vars: awsutils_vars
#  - include_vars: "{{ region }}"

  - include_vars: us-east-1
    when: region == "us-east-1"
  - include_vars: us-west-2
    when: region == "us-west-2"
  - include_vars: eu-west-1
    when: region == "eu-west-1"
  - include_vars: sp-southeast-1
    when: region == "sp-southeast-1"

  - name: Launch new instance(s)
    local_action:
      module: ec2
      count: "{{ awsutils_instance_count }}"
      instance_type: "{{ awsutils_instance_type }}"
      image: "{{ ec2.ami.amazon_linux_is_hvm }}"
      region: "{{ region }}"
      vpc_subnet_id: "{{ ec2.vpc.private.b }}"
      group_id: "{{ ec2.sg.private0 }}"       
      key_name: "{{ ec2.kp.johnnesselt }}"
      monitoring: no 
      assign_public_ip: no
      wait: yes
      wait_timeout: 500
    register: ec2info

  - name: Tag launched instance(s)
    local_action:
      module: ec2_tag
      resource: "{{ item.1.id }}"
      region: "{{ region }}"
      tags:
        Name: "AWSUtils"
        system: awsutils
        environment: "{{ env }}"
        account: john.nesselt@proquest.com
    with_indexed_items: ec2info.instances

  - name: Add all instance private IPs to host group
    local_action: add_host hostname={{ item.private_ip }} groupname=tag_system_awsutils
    with_items: ec2info.instances

  - name: Waiting for SSH to come up
    local_action: wait_for host={{ item.private_ip }} port=22 delay=60 timeout=300 state=started
    with_items: ec2info.instances

#  - name: Install awsutils on EC2 Instance(s)
#    include: configure-awsutils.yml
